In [1]:
using DelimitedFiles

In [6]:


function get_vizinhos_one_flip(solucao, tamanho)
    vizinhos = Vector()
    for indice in 1:tamanho-1
        vizinho = copy(solucao)
        vizinho[indice], vizinho[indice+1] = solucao[indice+1], solucao[indice]
        push!(vizinhos, vizinho)
    end
    vizinho = copy(solucao)
    vizinho[1], vizinho[tamanho] = solucao[tamanho], solucao[1]
    push!(vizinhos, vizinho)
    return vizinhos
end

get_vizinhos_one_flip (generic function with 1 method)

In [7]:
function get_melhor_vizinho(vizinhos, is_first_improved, menor_custo, melhor_solucao, tamanho)
    for vizinho in vizinhos
        _, custo = get_custo(vizinho, tamanho, 0)
        if custo < menor_custo
            menor_custo = custo
            melhor_solucao = vizinho
            if is_first_improved
                break
            end
        end
    end
    return melhor_solucao, menor_custo
end

get_melhor_vizinho (generic function with 1 method)

In [5]:
instancia = readdlm("pfssp/data/fs/ta001", Int, skipstart=1)

20×10 Matrix{Int64}:
 0  54  1  79  2  16  3  66  4  58
 0  83  1   3  2  89  3  58  4  56
 0  15  1  11  2  49  3  31  4  20
 0  71  1  99  2  15  3  68  4  85
 0  77  1  56  2  89  3  78  4  53
 0  36  1  70  2  45  3  91  4  35
 0  53  1  99  2  60  3  13  4  53
 0  38  1  60  2  23  3  59  4  41
 0  27  1   5  2  57  3  49  4  69
 0  87  1  56  2  64  3  85  4  13
 0  76  1   3  2   7  3  85  4  86
 0  91  1  61  2   1  3   9  4  72
 0  14  1  73  2  63  3  39  4   8
 0  29  1  75  2  41  3  41  4  49
 0  12  1  47  2  63  3  56  4  47
 0  77  1  14  2  47  3  40  4  87
 0  32  1  21  2  26  3  54  4  58
 0  87  1  86  2  75  3  77  4  18
 0  68  1   5  2  77  3  51  4  68
 0  94  1  77  2  40  3  31  4  28

In [35]:
instancia[:, setdiff(1:end, [column for column in 1:size(instancia)[2] if (column % 2) == 1])]

20×5 Matrix{Int64}:
 54  79  16  66  58
 83   3  89  58  56
 15  11  49  31  20
 71  99  15  68  85
 77  56  89  78  53
 36  70  45  91  35
 53  99  60  13  53
 38  60  23  59  41
 27   5  57  49  69
 87  56  64  85  13
 76   3   7  85  86
 91  61   1   9  72
 14  73  63  39   8
 29  75  41  41  49
 12  47  63  56  47
 77  14  47  40  87
 32  21  26  54  58
 87  86  75  77  18
 68   5  77  51  68
 94  77  40  31  28

In [24]:
for linha in eachcol(instancia)
    println(linha)
end

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[54, 83, 15, 71, 77, 36, 53, 38, 27, 87, 76, 91, 14, 29, 12, 77, 32, 87, 68, 94]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[79, 3, 11, 99, 56, 70, 99, 60, 5, 56, 3, 61, 73, 75, 47, 14, 21, 86, 5, 77]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
[16, 89, 49, 15, 89, 45, 60, 23, 57, 64, 7, 1, 63, 41, 63, 47, 26, 75, 77, 40]
[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
[66, 58, 31, 68, 78, 91, 13, 59, 49, 85, 85, 9, 39, 41, 56, 40, 54, 77, 51, 31]
[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
[58, 56, 20, 85, 53, 35, 53, 41, 69, 13, 86, 72, 8, 49, 47, 87, 58, 18, 68, 28]


In [13]:
tamanho = size(instancia)

(20, 10)

In [ ]:
matrix_custo = zeros(Int, tamanho)

In [19]:
matrix_custo = zeros(Int, tamanho)
for linha in 2:tamanho[1]
    for coluna in 2:tamanho[2]
        matrix_custo[linha, coluna] = instancia[linha, coluna] + max(matrix_custo[linha-1, coluna], matrix_custo[linha, coluna-1])
    end
end

In [20]:
matrix_custo

20×10 Matrix{Int64}:
 0     0     0     0     0     0     0     0     0     0
 0    83    84    87    89   178   181   239   243   299
 0    98    99   110   112   227   230   270   274   319
 0   169   170   269   271   286   289   357   361   446
 0   246   247   325   327   416   419   497   501   554
 0   282   283   395   397   461   464   588   592   627
 0   335   336   494   496   556   559   601   605   680
 0   373   374   554   556   579   582   660   664   721
 0   400   401   559   561   636   639   709   713   790
 0   487   488   615   617   700   703   794   798   811
 0   563   564   618   620   707   710   879   883   969
 0   654   655   716   718   719   722   888   892  1041
 0   668   669   789   791   854   857   927   931  1049
 0   697   698   864   866   907   910   968   972  1098
 0   709   710   911   913   976   979  1035  1039  1145
 0   786   787   925   927  1023  1026  1075  1079  1232
 0   818   819   946   948  1049  1052  1129  1133  1290
 0   905  